apiVersion: v1
kind: Service
metadata:
  name:  ronnie-rtp-service
  namespace: ronnie
spec:
  type: NodePort
  selector:
    app: ronnie-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
